### ISSUE TITLE
TTL not working

### ISSUE THREAD

**Issue by nikhil32** [web-push-libs/web-push#174]
Hi,

I am trying to include TTL key in sendNotification call with a time of 10 seconds. I closed my browser for 1 minute and then I reopened the browser and I can able to see my notification. I am not sure whether I am making something wrong. 

Thanks in advance....

**Comment by marco-c** [comment]
Related: http://stackoverflow.com/questions/37853024/ttl-feature-not-working-on-google-chrome-push-notification

The problem is that the library supports the TTL for standard web push endpoints but not for GCM ones. I'm not sure if it's worth it to add support for TTL to GCM, since Chrome is soon going to use the standard web push protocol.

@gauntface what do you think?

**Comment by nikhil32** [comment]
@marco-c that question was posted by me only. No one replied for that as well.

**Comment by gauntface** [comment]
I'll raise a PR later this week to move Chrome behaviour over to web push. Sorry I've been delayed doing this as I've been moving from Europe to the States.

**Comment by nikhil32** [comment]
Thanks for your inputs

**Comment by marco-c** [comment]
This will be fixed by #180.
