### ISSUE TITLE
Version 2.2.0 no response

### ISSUE THREAD

**Issue by felixsanz** [web-push-libs/web-push#195]
In 2.1.1 when you do `webPush.sendNotification(obj).then(response => { })`, the object `response` was JSON with success/failure. Now that object doesn't even exist.

So how i do know if the message was sent, succeed or failed? I'm removing subscriptions after 3+ fails (because my backend maybe didn't notified of the unsubscription), but now i don't know how to manage that! :)

**Comment by marco-c** [comment]
I think we haven't changed anything regarding the result of the promise (it's rejected when there's an error, it's resolved using the body of the response from the push service otherwise).
Can you double-check if you have different results when using 2.1.1 vs 2.2.0?

By the way, the best way to know whether the message has been successfully sent or not is to rely on the resolution/rejection of the promise returned by `sendNotification`. The promise is resolved when there was no error sending the message, rejected otherwise.

**Comment by felixsanz** [comment]
I can confirm that 2.1.1 returns me this kind of objects:

```
{"multicast_id":7475488619894565787,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1469334871372633%982969baf9fd7ecd"}]}
{"multicast_id":8120753148901927753,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1469361461247542%fb7f7f01d9fd7ecd"}]}

```

While 2.2.0 returns me nothing. empty. Catch is not catching anything also

**Comment by felixsanz** [comment]
By the way, **notifications arrive** so everything seems to work **except the response**.

Here is how i do it, just in case i'm doing it wrong:

```javascript
const pushPromises = results.map(subscription => webPush.sendNotification(subscription.endpoint, {
  payload: JSON.stringify({
    body: 'Test',
  }),
  userPublicKey: subscription.keys.p256dh,
  userAuth: subscription.keys.auth,
}).then(response => {
   console.log('r ', response) // this just prints "r" and nothing more
}).catch(e => {
  console.log(e) // nothing
}))

await Promise.all(pushPromises).then((x) => {
  console.log('x', x) // [ undefined, undefined ]
}).catch(e => {
  console.log(e) // nothing
})
```

**Comment by marco-c** [comment]
> While 2.2.0 returns me nothing. empty. Catch is not catching anything also

Catch is not catching anything because the notification was successfully sent. The promise will be rejected only if there's an error while sending the notification.

The difference you're seeing is due to Google Chrome switching from GCM (old proprietary protocol) to FCM (Web Push standard protocol).
The response with the Web Push protocol has an empty body.

To summarize, don't rely on the response, only rely on whether the promise is resolved or rejected. It is resolved on success, rejected on failure (try with a non-existing endpoint and you'll see that the promise is rejected).
When it is rejected, it's rejected to a `WebPushError` object, e.g.:
```
{ [WebPushError: Received unexpected response code]
  name: 'WebPushError',
  message: 'Received unexpected response code',
  statusCode: 400,
  headers: 
   { 'access-control-allow-headers': 'content-encoding,encryption,crypto-key,ttl,encryption-key,content-type,authorization',
     'access-control-allow-methods': 'POST',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'location,www-authenticate',
     'content-type': 'application/json',
     date: 'Sun, 24 Jul 2016 13:05:31 GMT',
     server: 'cyclone/1.1',
     'content-length': '51',
     connection: 'Close' },
  body: '{"errno": 102, "code": 400, "error": "Bad Request"}' }
```

**Comment by gauntface** [comment]
That's because gcm now uses web push protocol which doesn't return a json
response.

**Comment by felixsanz** [comment]
So basically now the rejected promise can be both "error sending" and "sent but error in response" ?

**Comment by marco-c** [comment]
> So basically now the rejected promise can be both "error sending" and "sent but error in response" ?

The rejected promise means (and I think it has always meant) that there was an error while sending the push notification, that is the push notification was not sent.

**Comment by felixsanz** [comment]
Yea, i mean:

```
webPush.sendNotification(subscription.endpoint, { obj }).catch(e => {})
```

This catch is executed when both:

1. Push IS NOT sent because of an error (malformed obj, network?, etc)
2. Push IS sent but the subscription is unauthorized

I think both things should be separate. Having a `.then(response => response.headers.statusCode === 400)` (like GCM before) seems better than using `catch`. Why throw an exception when the request was sent successfully?

**Comment by gauntface** [comment]
Can you provide an example of when it's unauthorized / how I can reproduce? Is it a bad GCM API key?

As an FYI GCM and FCM support web push protocol. The changes I made means the authorisation header is still required for GCM requests.

**Comment by felixsanz** [comment]
unauthorized is just subscribe, save the endpoint/keys to server, and then unsubscribe from the browser without notifying the server.

the server will try to send push notifications to that endpoint but the push service returns 400. That "error" should be part of `.then()`, not part of `.catch()` because it's not an exception, it's just a KO response.

another side question: do i still need `setGCMAPIKey` and manifest's `gcm_sender_id` now in 2.2.0 ?

**Comment by gauntface** [comment]
yes you do need the GCM API if you have any GCM endpoints you want to send messages to (which you will continue to receive from older versions of Chrome, Samsung Browser and Opera for Android).

If you implement VAPID (Blog post coming out soon on developers.google.com) Chrome will give you a non-GCM endpoint.

Just tried reproducing - it's expected behaviour. 400 when the subscription had been unsubscribed, no notification was shown and catch was thrown.

I think most (if not all developers) will expect the promise to resolve when the sendNotification was successful (i.e. the push service said everything was ok). If anything is wrong (i.e. the push is not going to be sent) then the promise should reject - as it currently is.

**Comment by felixsanz** [comment]
> If you implement VAPID Chrome will give you a non-GCM endpoint.

But older versions, samsung and opera still use GCM right?

The other "issue", thats the API design and i'm ok with that. Thanks for clearing it out

**Comment by gauntface** [comment]
Yeah, they will require the gcm_sender_id and will return a GCM endpoint.
