### ISSUE TITLE
Support Web Push Channel Aggregation

### ISSUE THREAD

**Issue by vibgy** [web-push-libs/web-push#206]
Services use pub-sub topics to deliver one-to-many push messages. Wondering if pub-sub topics can be implemented with web-push?

**Comment by marco-c** [comment]
https://tools.ietf.org/html/draft-ietf-webpush-protocol-08#section-5.4

Autopush doesn't support it yet (https://github.com/mozilla-services/autopush/issues/643), I don't know if FCM supports it.

**Comment by marco-c** [comment]
Sorry, I think you meant https://martinthomson.github.io/webpush-aggregate/. It isn't implemented by anyone yet.

**Comment by gauntface** [comment]
That webpush-aggragate doc is super old "Expires: April 11, 2015". Topic support isn't an easy task because a single topic message would need to be encrypted for every single topic subscriber.

Best bet would for a library to implement topic utilising this library to perform the encryption and sending.
