### ISSUE TITLE
Need to change aesgcm to aesgcm128 for Content-Encoding

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/web-push#238]
Relevant section: https://tools.ietf.org/html/draft-ietf-webpush-encryption-03#section-3.2

**Comment by marco-c** [comment]
This is a bit confusing, because for https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-02, content-encoding is `aesgcm`.

Autopush currently fails if you use `Content-Encoding: aesgcm128` and have a `Crypto-Key` header:
https://github.com/mozilla-services/autopush/blob/cf74d402ad575863ea3c1b286ab3144f040e2204/autopush/web/push_validation.py#L172
https://github.com/mozilla-services/autopush/blob/cf74d402ad575863ea3c1b286ab3144f040e2204/autopush/endpoint.py#L392

Firefox as well:
https://dxr.mozilla.org/mozilla-central/rev/da986c9f1f723af1e0c44f4ccd4cddd5fb6084e8/dom/push/PushCrypto.jsm#65

ping @kitcambridge

**Comment by kitcambridge** [comment]
Huh, I thought `aesgcm` was the *new* encoding, and `aesgcm128` was the old-and-busted one. @martinthomson, does draft-ietf-webpush-encryption need updating?
