### ISSUE TITLE
GCM is needed for web-push ? Can we use without any third party ?

### ISSUE THREAD

**Issue by v3ss0n** [web-push-libs/web-push#259]
Does web-push work without GCM , in Latest Chrome ? GCM is a must?

**Comment by marco-c** [comment]
It does work without GCM too, if you use VAPID.

**Comment by antsmartian** [comment]
I can understand this issue is closed, but is there any example in which VAPID is used without GCM?

**Comment by MartijnDwars** [comment]
Using VAPID without GCM isn't anything special:

1. In the backend, don't call `webpush.setGCMAPIKey('<Your GCM API Key Here>');`. Only call `webpush.setVapidDetails`.
2. In the frontend, provide a `applicationServerKey` when calling `pushManager.subscribe`.
3. Don't create a web app manifest.

**Comment by antsmartian** [comment]
@MartijnDwars Thanks got it working! One noob question, I guess when we get `subscription` object from the UI, the endpoint looks like `https://fcm.googleapis.com/fcm/send/***` (for chrome). So when we call `sendNotification` using `web-push` - we do actually send the push request to `fcm` end point right (which then pushes the notification to the browser)?

Can I deploy my *own* push server like `fcm` or `updates.push.services.mozilla.com`  so that I can do the pushing? I guess that's not possible, but still checking if there is a way to do so. 

Thanks!

**Comment by MartijnDwars** [comment]
> we do actually send the push request to fcm end point right (which then pushes the notification to the browser)?

Right.

> Can I deploy my own push server like fcm or updates.push.services.mozilla.com so that I can do the pushing?

Well, Chrome will register the subscription with Google, Firefox with Mozilla, etc. You can probably create your own browser that uses it's own push server, or maybe modify the existing Browsers to use a different push server, but I don't see the point in doing that.

**Comment by v3ss0n** [comment]
>  but I don't see the point in doing that

Many uses caes , for privacy sensitve application / Goverment projects. where push notification should not go tru GCM/FCM/APPL

**Comment by antsmartian** [comment]
@v3ss0n Exactly. But doing so is not easy or not even possible I guess. Since each browser give the endpoint very tightly coupled to their push servers. Not sure, if we can reach to the browser without those endpoints.

**Comment by marco-c** [comment]
With Firefox you could use a custom Web Push service by changing the dom.push.serverURL preference.

It's not feasible to ask users to change this preference, but for organizations and governments where Firefox is usually deployed centrally this is feasible.
