### ISSUE TITLE
Cordova support

### ISSUE THREAD

**Issue by awebdeveloper** [web-push-libs/web-push#271]
Can we also add Cordova support for Android (atleast) and iOS.

Thanks

**Comment by marco-c** [comment]
Cordova support might be out of scope for this library. Perhaps someone could build a Cordova plugin using this library.

**Comment by NoNameProvided** [comment]
I am not sure how you mean support. Android should be supported already because the webview is basically a Chrome instance. So you can simply register yourself for push notifications just like you would do it on a webpage. Safari isn't supported right now but as soon as the required features will be implemented in Safari it will be supported as well.

**Comment by gauntface** [comment]
I don't believe WebView supported service workers and I don't believe it works with Push.

WebView === Chromium but WebView !== Chrome.

Secondly - WebViews on each platform have API's that can enable / disable features of the web platform.

You'd be better served using a Cordova Plugin that uses native platform API's to register for push and expose those API's in your hybrid app.

**Comment by macdonst** [comment]
As the maintainer of [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) I can tell you this request does not make sense. The Android webview already supports receiving web push and this node package can't add the functionality to the iOS web view for Cordova. That is why the above plugin exists.

**Comment by awebdeveloper** [comment]
if i am not wrong this is a server that sends push notification. I am asking for the server to support [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) not find a replacement for it.

**Comment by NoNameProvided** [comment]
When you push to GCM (FCM) or APN with web-push library users will receive the same push notification via `phonegap-plugin-push` if you used the same key.

**Comment by gauntface** [comment]
This library is for "web push" - i.e. push services that implement the web push protocol for push supporting browsers.

Cordova + Plugins will support push via the native platforms push provider (I.e. Firebase Cloud Messagne and APNS).

Your server will need to make requests using those proprietary APIs. For Android you could look for something like: https://www.npmjs.com/package/fcm-push (Although the request is a simple POST message).

Going to close this issue as agreed - this issue is not relevant to this library.
