### ISSUE TITLE
web-push FROM browser

### ISSUE THREAD

**Issue by Zibri** [web-push-libs/web-push#351]
Using VAPID I am able to send a push notification from any computer running node and web-push knowing only the endpoint and the "keys" associated with VAPID.

I tried to use browserify to have web-push as a bundle I can import in a browser.

The problem seems that running web-push in the browser gives an XSS/CORS error.
Obviously that does not happen if I disable web browser security.

Is there any way to directly send a push notification from a browser (i.e. static web page)
Without using firebase or any other server just knowing the credentials and endpoint?

Thanks for reading.

**Comment by Zibri** [comment]
Update: I changed "mode: 'cors'" in the fetch request, with " mode: 'no-cors' "
Now instead of the XSS error I get a 400 error from the server.
How to solve that?
Is there any way, without using firebase account to directly send a notification FROM a web browser to ANOTHER web browser knowing the credentials and endpoints?

**Comment by subversivo58** [comment]
Hmm ... I tried this for a decentralized application using WebRTC and a logic similar to **"Smart Contracts"** where the administrator (the one who created the contract) could send notifications.

I tested this some previous releases and the problem I found was incompatibility in a cryptographic process, it seems to me that **Browserify** was not fully compliant with `crypto.js` module.

As I was using a signaling server (WebSockets) I ended up opting to send the user credentials to the same server :confused: 

@Zibri in your update it seems that you could not understand the process which is as follows:

It is not possible to send browser notifications to the browser ... the **Push** service (in this case the endpoint) is responsible for this task.

The library itself works with Promises and waits for an endpoint response

I am also curious about whether this is possible, maybe someone with more knowledge about the library and the protocol can help to clarify better.

**Comment by Zibri** [comment]
I totally understand the process.
But there is an error somewhere.
I am able to send a notification to an endpoint or a group from a browser.
I am just not able to do it using the "more comfortable" web-push library.
The same code works in nodejs but does not in a browser.
If as you suggest, the problem is browserify, can you provide a way to use the library from within a browser?

**Comment by subversivo58** [comment]
In **nodejs** the library sends to the endpoint the credentials of the user (browser) and the encrypted content (payload) and options like TTL ... I'm not sure how each service treats the request but it (the service) returns an answer.

The library handles this request (and replaces) in a Promise, rejecting or confirming depending on the response of the endpoint.

As I said above: I tried to follow this same logic but, at that time the error was encryption ... I had to manually debug the **Browserify** package to find the error, it was time consuming to find it, there was no exception involving the error.

I do not know how the service handles the request, but it seems to me that it is not just a simple `POST` method, is a `Stream` using the `.request()` method of **"https"** module ... I may be wrong but this is the stretch where the library makes the request to the endpoint:


https://github.com/web-push-libs/web-push/blob/master/src/web-push-lib.js#L271,#L341

```javascript
/**
 * To send a push notification call this method with a subscription, optional
 * payload and any options.
 * @param  {PushSubscription} subscription The PushSubscription you wish to
 * send the notification to.
 * @param  {string} [payload]              The payload you wish to send to the
 * the user.
 * @param  {Object} [options]              Options for the GCM API key and
 * vapid keys can be passed in if they are unique for each notification you
 * wish to send.
 * @return {Promise}                       This method returns a Promise which
 * resolves if the sending of the notification was successful, otherwise it
 * rejects.
 */
WebPushLib.prototype.sendNotification =
  function(subscription, payload, options) {
    let requestDetails;
    try {
      requestDetails = this.generateRequestDetails(subscription, payload, options);
    } catch (err) {
      return Promise.reject(err);
    }

    return new Promise(function(resolve, reject) {
      const httpsOptions = {};
      const urlParts = url.parse(requestDetails.endpoint);
      httpsOptions.hostname = urlParts.hostname;
      httpsOptions.port = urlParts.port;
      httpsOptions.path = urlParts.path;

      httpsOptions.headers = requestDetails.headers;
      httpsOptions.method = requestDetails.method;

      if (requestDetails.proxy) {
        httpsOptions.agent = new HttpsProxyAgent(requestDetails.proxy);
      }

      const pushRequest = https.request(httpsOptions, function(pushResponse) {
        let responseText = '';

        pushResponse.on('data', function(chunk) {
          responseText += chunk;
        });

        pushResponse.on('end', function() {
          if (pushResponse.statusCode < 200 || pushResponse.statusCode > 299) {
            reject(new WebPushError(
              'Received unexpected response code',
              pushResponse.statusCode, pushResponse.headers, responseText, requestDetails.endpoint
            ));
          } else {
            resolve({
              statusCode: pushResponse.statusCode,
              body: responseText,
              headers: pushResponse.headers
            });
          }
        });
      });

      pushRequest.on('error', function(e) {
        reject(e);
      });

      if (requestDetails.body) {
        pushRequest.write(requestDetails.body);
      }

      pushRequest.end();
    });
  };
```

As stated: you can not send a notification directly from your browser to another browser even if you have the credentials of this other browser ... you must send your notification to the endpoint and it is he who will send this notification to the other browser.

I can not tell you what your mistake is, I'm not sure if it's possible to go through **nodejs** and go directly to the endpoint, but maybe it's a good way to check if the **Browserify** packet is making a `Stream` request.

I am also curious about a qualified word.

Accompanying this issue :smile:

**Comment by Zibri** [comment]
I know I can't send it to another browser! I mean using the endpoint!
With firebase everything works... but I wish to directly send to the endpoint using VAPID. That's it.

**Comment by subversivo58** [comment]
@Zibri this depends on each browser and underlying system e.g:

+ Apple APNS (Apple Push Notification Service) (iOS/Mac OS X)
+ Google GCM/FCM (Google Cloud Messaging/Firebase Cloud Messaging) (Chrome/Chromium/Android)
+ Mozila Autopush (Mozilla Push server and Push Endpoint) (Firefox/Firefox OS)
+ Windows WNS (Windows Push Notification Services) (UWP)
+ Microsoft MPNS (Microsoft Push Notification Service) (Windows Phone 8)
+ Amazon ADM (Amazon Device Messaging) (by [SNS](https://aws.amazon.com/pt/sns/))
+ Baidu Cloud Push (Baidu Cloud Push SDK)
+ Tizen SPPCD (Samsung Push Service) (Tizen OS)

> NOTES:
>
> + for example in the above list APNS can be used both in the device (iOS / Mac OS X) and in a watchOS 3 or later ... the system decides which device received the notification. See more details in [the official documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/WatchKitProgrammingGuide/BasicSupport.html).
>
> + Auto Push is used in Mozilla's mobile system as well as to meet the [Web Push](https://datatracker.ietf.org/doc/draft-ietf-webpush-protocol/) specification in web applications using Firefox. See more details in [the official documentation](https://autopush.readthedocs.io/en/latest/).
>
> + Windows WNS is used in UWP (Universal Windows Platform) that integrates the connected services of the tenth (10) version of this OS.

This demo test and show browser credentials (see endpoint): https://gauntface.github.io/simple-push-demo/


If you test with Chrome (desktop 64bits) the endpoint will look something like this:

```json
{
 "endpoint":"https://fcm.googleapis.com/fcm/send/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "expirationTime": null,
 "keys": {
    "p256dh":"yyyyyyyyyyyyyyyyyyyyyyyy",
    "auth":"xxxxxxxxxxxxxxx"
  }
}
```

If you test with Firefox (desktop 64bits) the endpoint will look something like this:

```json
{
 "endpoint": "https://updates.push.services.mozilla.com/wpush/v2/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "expirationTime": null,
 "keys": {
    "p256dh":"yyyyyyyyyyyyyyyyyyyyyyyy",
    "auth":"xxxxxxxxxxxxxxx"
  }
}
```
The above demo follows the pattern, although it has a button ("SEND A PUSH VIA XHR") it sends to the backend and the backend sends it to the endpoint :confused:

To bring "more light" to the question it seems to me that this is a limitation of the service (endpoint) in this case of the own `https://fcm.googleapis.com/fcm/send/`

I did a quick search and found no official documentation, the closest I got to because FireBase Cloud Message returns an error regarding `CORS` was through this issue in the [stackoverflow.com](https://stackoverflow.com/questions/36691533/how-to-send-push-notifications-in-chromeprogressive-web-apps/36717282#36717282)

I made a demo following this logic (use Browserify in the web-push library) ... I tested using:

+ **Chrome**: version 67.0.3396.99 (64 bit) on Ubuntu 18.04 LTS (64 bit)
+ **Chrome**: version version 67.0.3396.99 on Android  7.1.2 (ARM)
+ **Firefox**: version 60.0.2 (64 bit) on Ubuntu 18.04 LTS (64 bit)
+ **Firefox**: version version 60.0.1 on Android  7.1.2 (ARM)

I could not debug the mobile tests but as expected Chrome presented a CORS error.

Firefox on the other hand worked perfectly for both the desktop and the mobile browser.

I was not able to test with other services (endpoints) but, it is very probable that they could also present errors related to `CORS`.

For the sake of curiosity and to try to "circumvent" this limitation of FCM I used in my demo the demonstration url of module [cors-anywhere](https://github.com/Rob--W/cors-anywhere) which serves as a proxy.

Although it works, avoid using this demo in production, you can create your own application in Heroku using this library, read carefully the **"Demo server"** section described in the project [README](https://github.com/Rob--W/cors-anywhere#demo-server)

> A brief description:

In my demo I exported the library to the `window` object, I edited the file generated by **Browserify** to check if the url to be requested is referring to the **FCM** you can see on the lines [29015 to 29027](https://github.com/subversivo58/lab/blob/master/assets/js/webpush-browserify-bundle.js#L29025,L29027)

FCM requisitions now work using both desktop and mobile Chrome

I hope this helps the issue.

> Notes:
+ 1: Do not expose your VAPID private key in the frontend ... the logic to preserve the private key has not been addressed in my demo, this is at developer's discretion
+ 2: There are no warranties for use in producing the source code of my demo

> References:

+ [how to make a request to GCM to send a notification via XHR](https://stackoverflow.com/questions/36662561/how-to-make-a-request-to-gcm-to-send-a-notification-via-xhr/36894224#36894224)
+ [How to send push notifications in Chrome(Progressive Web Apps)](https://stackoverflow.com/questions/36691533/how-to-send-push-notifications-in-chromeprogressive-web-apps/36717282#36717282)
+ [Disabling CORS using js fetch [duplicate]](https://stackoverflow.com/questions/41030425/disabling-cors-using-js-fetch#41030457)
+ [cors-anywhere (GitHub project)](https://github.com/Rob--W/cors-anywhere)
+ [cors-anywhere demo app (Heroku)](https://cors-anywhere.herokuapp.com/)

> Demo links:

+ [demo page](https://subversivo58.github.io/lab/webpush-test.html)
+ [demo web-push Browserify bundle](https://github.com/subversivo58/lab/blob/master/assets/js/webpush-browserify-bundle.js)
+ [demo main.js](https://github.com/subversivo58/lab/blob/master/assets/js/webpush-browser-to-endpoint-test.js)
+ [demo sw.js](https://github.com/subversivo58/lab/blob/master/webpush-sw.js)

**Comment by marco-c** [comment]
It would be a little weird given how VAPID is supposed to work, but I can't think of anything preventing Web Push from working in the browser.
I will close this issue as I don't intend to support this use case, but if you manage to find a fix feel free to submit a PR and I will accept it.

**Comment by Zibri** [comment]
I tested it again and I can successfully SEND push notification usign a browser!
I used this: https://github.com/subversivo58/lab/blob/master/assets/js/webpush-browserify-bundle.js
