### ISSUE TITLE
API for generating raw request to FCM

### ISSUE THREAD

**Issue by marcoroganovic** [web-push-libs/web-push#429]
Hi!

I'm using Node.js for sending push notifications, but I can't achieve number of successfully sent notifications in one hour with it, even though I use multiple processes to issue requests.

So, I wanted to test some lower level language as a HTTP client to send notifications to FCM, and other providers. I've modified `sendNotification` method to return formatted request, but when I send request meta data to another server (endpoint, and headers), notifications are not delivered. And it says that registration failed, even though I can send notification with regular `sendNotification` call that returns Promise.

Regards,
Marco

**Comment by marco-c** [comment]
You shouldn't need modifications to `sendNotification`, you can use the `generateRequestDetails` to get the parameters to send for your HTTP request.

`sendNotification` is not doing much on top of `generateRequestDetails`, if you mirror that with a lower level HTTP request it should work.

I can't help you much without additional details, but this seems like an issue in your code rather than in the library.
