### ISSUE TITLE
Getting 406 error for Microsoft Edge (Version 91.0.864.59) while sending notification. 

### ISSUE THREAD

**Issue by pvagare** [web-push-libs/web-push#677]
# Setup

*Operating System*:  Linux
*Node Version*: 12
*web-push Version*: 3.4.4

- [ ] Microsoft Edge Latest version

# Problem

From yesterday I am getting 406 error for Microsoft Edge notification. I looked on internet and found that status code 406  meaning . 

Is this correct behavior ? 
Here is explanation from link:
https://stackoverflow.com/questions/18287746/windows-phone-push-notifications-406-not-acceptable

"This isn't an error you should (or could) do something about. It just means that you sent too many notifications to the same device or too many notifications per second, and you have to wait until you can send more. "

 
# Expected

Can you tell me how to avoid this 406 status code error for Microsoft edge? Or am I missing something ? Please can you look into this? I am getting issue on my Production. it will be good help If you able to find quick solution on this?

# Features Used

- [x] VAPID Support

**Comment by marco-c** [comment]
If the problem is `This isn't an error you should (or could) do something about. It just means that you sent too many notifications to the same device or too many notifications per second, and you have to wait until you can send more.`, then you just need to rate limit and avoid sending too many notifications to the same device in a short timeframe.
