### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by cirolosapio** [web-push-libs/web-push#904]
# Setup

*web-push Version*: 3.6.7

- [x] Chrome
- [x] Firefox
- [x] Opera for Android
- [x] Samsung Internet Browser
- [ ] Other

# Problem

in a deno deploy environment the sendNotification works only without a payload

# Expected

it should work with payload also

# Features Used

- [x] VAPID Support
- [ ] GCM API Key
- [x] Sending with Payload

# Example / Reproduce Case

[server](https://github.com/cirolosapio/deno-web-push)

**Comment by ktn1234** [comment]
Currently, the reason why it works in Deno environment without a payload is because the browser recipient that receives the notification payload doesn't have anything to decrypt so it'll work fine. 

If you add a payload, and run `sendNotification` in Deno environment, the browser recipient needs to decrypt the notification payload it but it can't. This might have to do with how Deno's encryption implementation details work vs Node.js. 

If you are using chrome as the browser recipient and observe the message logs using `chrome://gcm-internals` and attempt to use `sendNotification` with a payload, you will get a `AES-GCM decryption failed` in the Message Decryption Failure Log like so:

<img width="1033" alt="Screenshot 2024-07-04 at 3 03 37 PM" src="https://github.com/web-push-libs/web-push/assets/22810111/30328100-031d-4417-8d1f-17efe7469a6f">

**Comment by ktn1234** [comment]
I am using the following Deno version:
```
deno 1.44.4 (release, x86_64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

Currently, the reason why it works in Deno environment **without** a payload is because the browser recipient that receives the notification payload doesn't have anything to decrypt so it'll work fine. 

If you add a payload, and run `sendNotification` in Deno environment, the browser recipient needs to decrypt the notification payload it but it can't. This might have to do with how Deno's encryption implementation details work vs Node.js. 

If you are using chrome as the browser recipient and observe the message logs using `chrome://gcm-internals` and attempt to use `sendNotification` with a payload in a Deno environment (for me, **Deno 1.44.4**), you will get a `AES-GCM decryption failed` in the Message Decryption Failure Log like so:

<img width="1033" alt="Screenshot 2024-07-04 at 3 03 37 PM" src="https://github.com/web-push-libs/web-push/assets/22810111/30328100-031d-4417-8d1f-17efe7469a6f">

**Comment by ktn1234** [comment]
I am using the following Deno version:
```
deno 1.44.4 (release, x86_64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

Currently, the reason why it works in Deno environment **without** a payload is because the browser recipient that receives the notification payload doesn't have anything to decrypt so it'll work fine. 

If you add a payload, and run `sendNotification` in Deno environment, the browser recipient needs to decrypt the notification payload it but it can't. This might have to do with Deno's encryption implementation details vs Node.js because it works perfectly fine for me with a payload in a Node.js environment (I tested using `node v21.2.0`). 

If you are using chrome as the browser recipient and observe the message logs using `chrome://gcm-internals` and attempt to use `sendNotification` with a payload in a Deno environment (for me, **Deno 1.44.4**), you will get a `AES-GCM decryption failed` in the Message Decryption Failure Log like so:

<img width="1033" alt="Screenshot 2024-07-04 at 3 03 37 PM" src="https://github.com/web-push-libs/web-push/assets/22810111/30328100-031d-4417-8d1f-17efe7469a6f">

**Comment by ktn1234** [comment]
I am using the following Deno version:
```
deno 1.44.4 (release, x86_64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

Currently, the reason why it works in Deno environment **without** a payload is because the browser recipient that receives the notification payload doesn't have anything to decrypt so it'll work fine. 

If you add a payload, and run `sendNotification` in Deno environment, the browser recipient needs to decrypt the notification payload it but it can't decrypt the payload upon receiving it. This might have to do with Deno's encryption implementation details vs Node.js because it works perfectly fine for me with a payload in a Node.js environment (I tested using `node v21.2.0`). 

If you are using chrome as the browser recipient and observe the message logs using `chrome://gcm-internals` and attempt to use `sendNotification` with a payload in a Deno environment (for me, **Deno 1.44.4**), you will get a `AES-GCM decryption failed` in the Message Decryption Failure Log like so:

<img width="1033" alt="Screenshot 2024-07-04 at 3 03 37 PM" src="https://github.com/web-push-libs/web-push/assets/22810111/30328100-031d-4417-8d1f-17efe7469a6f">

**Comment by alexgleason** [comment]
According to https://github.com/denoland/deno/issues/23693#issuecomment-2315268504 this is _actually actually_ fixed now.

**Comment by marco-c** [comment]
Thanks, that's good to hear!
